language: go
go: 1.9

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - make install_deps

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
