language: go
go: 1.9

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get github.com/kelseyhightower/envconfig
  - go get github.com/mitchellh/goamz/aws
  - go get github.com/mitchellh/goamz/s3
  - go get golang.org/x/oauth2
  - go get github.com/stacktic/dropbox

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
